---
- name: Get the config file
  slurp:
    src: "{{ config_file_path }}"
  register: config_file
- set_fact:
    config_file_decoded: "{{ config_file.content | b64decode }}"
- name: Apply the configmap update
  k8s:
    state: present
    definition:
      api_version: v1
      metadata:
        name: "{{ config_file_path | regex_replace('^.*\\/(.*)\\.json', '\\1') | lower }}"
        namespace: covid
      kind: ConfigMap
      data:
        appsettings.Production.json: |
            {{ config_file_decoded | to_json }}
    host: https://api.pro-eu-west-1.openshift.com:6443
    api_key: LNiq2nHdWxX1gnJh-kVEjQjkRUZ4N7YhEhqX97TfH6I
    apply: yes
