---

- name: Make a directory for the config 
  file:
    path: ./config
    state: directory
- name: Get the config files
  find:
    paths: /home/ec2-user/CovidCore/
    patterns: "appsettings*.json"
    use_regex: yes
    recurse: yes
  register: config_files
- set_fact:
    regex_filter: "^.*\\/(Covid.*)\\/appsettings\\.json"
- debug:
    msg: "{{ item.path | regex_replace('^.*\\/(Covid.*)\\/appsettings\\.Template\\.json', '\\1.json') }}"
  with_items:
    - "{{ config_files.files }}"
- name: Template the Appsettings files
  template:
    src: "{{ item.path }}"
    dest: "./config/{{ item.path | regex_replace('^.*\\/(Covid.*)\\/appsettings\\.Template\\.json', '\\1.json') }}"
  with_items:
    - "{{ config_files.files }}"
- name: Get a list of settings files to push into Openshift
  find: 
    paths: ./config/
  register: appsettings_files
- debug:
    msg: "{{ appsettings_files }}"
# - name: Apply the config to a ConfigMap in Openshift
#  k8s:
#    api_version: v1
#    kind: ConfigMap
#    namespace: covid
#    host: https://api.ca-central-1.starter.openshift-online.com:6443
#    api_key: ze47el0h0BwmD1zQklcgtF6HvC_atD27kuoPePERSLU
#    apply:  yes
#    name: 
#  register: service_list 
