apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: covid-pipeline
  namespace: covid
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/355gts/CovidCore.git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Deployment/covid.jenkinsfile 
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: lXgDq0_BH75lcCfrQ2_v
    type: GitHub
